[package]
name = "vaska"
version = "0.1.0"
authors = ["cyprien"]
edition = "2021"


[dependencies]
dioxus = { version = "0.8.0-alpha.1", features = ["router"] }
androxus = "0.1.7"
reqwest = { version = "0.13.5", features = ["json", "rustls"] }
webpki-root-certs = "1.0.9"
scraper = "0.27.0"

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15"
log = "0.4"
