[package]
name = "vaskar"
version = "0.1.0"
authors = ["cbdefontenay"]
edition = "2021"


[dependencies]
androxus = "0.1.7"
dioxus = { version = "0.8.0-alpha.1", features = ["router"] }
web-sys = { version= "0.3.106", features = ["Window", "Navigator", "Clipboard"] }
wasm-bindgen-futures = "0.4.79"

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]
